# Generated by Django 5.0.1 on 2024-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(default=50, max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(),
        ),
    ]
