# Generated by Django 5.0.1 on 2024-01-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0003_alter_teacher_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
