# Generated by Django 5.0.1 on 2024-01-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0004_alter_student_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
